// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lglomekhndqqicfszonw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnbG9tZWtobmRxcWljZnN6b253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNjc4NTMsImV4cCI6MjA2ODY0Mzg1M30.8_Tli3rLDe5VMpy4HR5eMHQmUcuwf_jDnee9aTFBPZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});